//
//  Neuromancer.swift
//  ReadSpeedster
//
//  Created by Andreas Antonsson on 2024-03-28.
//

import Foundation

struct TheMetamorphosis {
    let excerpt = """
'The Metamorphosis' by Franz Kafka

CHAPTER 1

When Gregor Samsa woke up one morning from unsettling dreams, he found himself changed in his bed into a monstrous vermin. He was lying on his back as hard as armor plate, and when he lifted his head a little, he saw his vaulted brown belly, sectioned by arch-shaped ribs, to whose dome the cover, about to slide off completely, could barely cling. His many legs, pitifully thin compared with the size of the rest of him, were waving helplessly before his eyes.

"What's happened to me?" he thought. It was no dream. His room, a regular human room, only a little on the small side, lay quiet between the four familiar walls. Over the table, on which an unpacked line of fabric samples was all spread out--Samsa was a traveling salesman--hung the picture which he had recently cut out of a glossy magazine and lodged in a pretty gilt frame. It showed a lady done up in a fur hat and a fur boa, sitting upright and raising up against the viewer a heavy fur muff in which her whole forearm had disappeared.

Gregor's eyes then turned to the window, and the overcast weather--he could hear raindrops hitting against the metal window ledge--completely depressed him. "How about going back to sleep for a few minutes and forgetting all this nonsense," he thought, but that was completely impracticable, since he was used to sleeping on his right side and in his present state could not get into that position. No matter how hard he threw himself onto his right side, he always rocked onto his back again. He must have tried it a hundred times, closing his eyes so as not to have to see his squirming legs, and stopped only when he began to feel a slight, dull pain in his side, which he had never felt before.

"Oh God," he thought, "what a grueling job I've picked! Day in, day out--on the road. The upset of doing business is much worse than the actual business in the home office, and, besides, I've got the torture of traveling, worrying about changing trains, eating miserable food at all hours, constantly seeing new faces, no relationships that last or get more intimate. To the devil with it all!" He felt a slight itching up on top of his belly; shoved himself slowly on his back closer to the bedpost, so as to be able to lift his head better; found the itchy spot, studded with small white dots which he had no idea what to make of; and wanted to touch the spot with one of his legs but immediately pulled it back, for the contact sent a cold shiver through him.

He slid back again into his original position. "This getting up so early," he thought, "makes anyone a complete idiot. Human beings have to have their sleep. Other traveling salesmen live like harem women. For instance, when I go back to the hotel before lunch to write up the business I've done, these gentlemen are just having breakfast. That's all I'd have to try with my boss; I'd be fired on the spot. Anyway, who knows if that wouldn't be a very good thing for me. If I didn't hold back for my parents' sake, I would have quit long ago, I would have marched up to the boss and spoken my piece from the bottom of my heart. He would have fallen off the desk! It is funny, too, the way he sits on the desk and talks down from the heights to the employees, especially when they have to come right up close on account of the boss's being hard of hearing. Well, I haven't given up hope completely; once I've gotten the money together to pay off my parents' debt to him--that will probably take another five or six years--I'm going to do it without fail. Then I'm going to make the big break. But for the time being I'd better get up, since my train leaves at five."

And he looked over at the alarm clock, which was ticking on the chest of drawers. "God Almighty!" he thought. It was six-thirty, the hands were quietly moving forward, it was actually past the half-hour, it was already nearly a quarter to. Could it be that the alarm hadn't gone off? You could see from the bed that it was set correctly for four o'clock; it certainly had gone off, too. Yes, but was it possible to sleep quietly through a ringing that made the furniture shake? Well, he certainly hadn't slept quietly, but probably all the more soundly for that. But what should he do now? The next train left at seven o'clock; to make it, he would have to hurry like a madman, and the line of samples wasn't packed yet, and he himself didn't feel especially fresh and ready to march around. And even if he did make the train, he could not avoid getting it from the boss, because the messenger boy had been waiting at the five-o'clock train and would have long ago reported his not showing up. He was a tool of the boss, without brains or backbone. What if he were to say he was sick? But that would be extremely embarrassing and suspicious because during his five years with the firm Gregor had not been sick even once. The boss would be sure to come with the health-insurance doctor, blame his parents for their lazy son, and cut off all excuses by quoting the health-insurance doctor, for whom the world consisted of people who were completely healthy but afraid to work. And, besides, in this case would he be so very wrong? In fact, Gregor felt fine, with the exception of his drowsiness, which was really unnecessary after sleeping so late, and he even had a ravenous appetite.

Just as he was thinking all this over at top speed, without being able to decide to get out of bed--the alarm clock had just struck a quarter to seven--he heard a cautious knocking at the door next to the head of his bed. "Gregor," someone called--it was his mother--"it's a quarter to seven. Didn't you want to catch the train?" What a soft voice! Gregor was shocked to hear his own voice answering, unmistakably his own voice, true, but in which, as if from below, an insistent distressed chirping intruded, which left the clarity of his words intact only for a moment really, before so badly garbling them as they carried that no one could be sure if he had heard right. Gregor had wanted to answer in detail and to explain everything, but, given the circumstances, confined himself to saying, "Yes, yes, thanks, Mother, I'm just getting up." The wooden door must have prevented the change in Gregor's voice from being noticed outside, because his mother was satisfied with this explanation and shuffled off. But their little exchange had made the rest of the family aware that, contrary to expectations, Gregor was still in the house, and already his father was knocking on one of the side doors, feebly but with his fist. "Gregor, Gregor," he called, "what's going on?" And after a little while he called again in a deeper, warning voice, "Gregor! Gregor!" At the other side door, however, his sister moaned gently, "Gregor? Is something the matter with you? Do you want anything?" Toward both sides Gregor answered: "I'm all ready," and made an effort, by meticulous pronunciation and by inserting long pauses between individual words, to eliminate everything from his voice that might betray him. His father went back to his breakfast, but his sister whispered, "Gregor, open up, I'm pleading with you." But Gregor had absolutely no intention of opening the door and complimented himself instead on the precaution he had adopted from his business trips, of locking all the doors during the night even at home.

First of all he wanted to get up quietly, without any excitement; get dressed; and, the main thing, have breakfast, and only then think about what to do next, for he saw clearly that in bed he would never think things through to a rational conclusion. He remembered how even in the past he had often felt some kind of slight pain, possibly caused by lying in an uncomfortable position, which, when he got up, turned out to be purely imaginary, and he was eager to see how today's fantasy would gradually fade away. That the change in his voice was nothing more than the first sign of a bad cold, an occupational ailment of the traveling salesman, he had no doubt in the least.

It was very easy to throw off the cover; all he had to do was puff himself up a little, and it fell off by itself. But after this, things got difficult, especially since he was so unusually broad. He would have needed hands and arms to lift himself up, but instead of that he had only his numerous little legs, which were in every different kind of perpetual motion and which, besides, he could not control. If he wanted to bend one, the first thing that happened was that it stretched itself out;* and if he finally succeeded in getting this leg to do what he wanted, all the others in the meantime, as if set free, began to work in the most intensely painful agitation. "Just don't stay in bed being useless," Gregor said to himself.

First he tried to get out of bed with the lower part of his body, but this lower part--which by the way he had not seen yet and which he could not form a clear picture of--proved too difficult to budge; it was taking so long; and when finally, almost out of his mind, he lunged forward with all his force, without caring, he had picked the wrong direction and slammed himself violently against the lower bedpost, and the searing pain he felt taught him that exactly the lower part of his body was, for the moment anyway, the most sensitive.

He therefore tried to get the upper part of his body out of bed first and warily turned his head toward the edge of the bed. This worked easily, and in spite of its width and weight, the mass of his body finally followed, slowly, the movement of his head. But when at last he stuck his head over the edge of the bed into the air, he got too scared to continue any further, since if he finally let himself fall in this position, it would be a miracle if he didn't injure his head. And just now he had better not for the life of him lose consciousness; he would rather stay in bed.

But when, once again, after the same exertion, he lay in his original position, sighing, and again watched his little legs struggling, if possible more fiercely, with each other and saw no way of bringing peace and order into this mindless motion, he again told himself that it was impossible for him to stay in bed and that the most rational thing was to make any sacrifice for even the smallest hope of freeing himself from the bed. But at the same time he did not forget to remind himself occasionally that thinking things over calmly--indeed, as calmly as possible--was much better than jumping to desperate decisions. At such moments he fixed his eyes as sharply as possible on the window, but unfortunately there was little confidence and cheer to be gotten from the view of the morning fog, which shrouded even the other side of the narrow street. "Seven o'clock already," he said to himself as the alarm clock struck again, "seven o'clock already and still such a fog." And for a little while he lay quietly, breathing shallowly, as if expecting, perhaps, from the complete silence the return of things to the way they really and naturally were.

But then he said to himself, "Before it strikes a quarter past seven, I must be completely out of bed without fail. Anyway, by that time someone from the firm will be here to find out where I am, since the office opens before seven." And now he started rocking the complete length of his body out of the bed with a smooth rhythm. If he let himself topple out of bed in this way, his head, which on falling he planned to lift up sharply, would presumably remain unharmed. His back seemed to be hard; nothing was likely to happen to it when it fell onto the carpet. His biggest misgiving came from his concern about the loud crash that was bound to occur and would probably create, if not terror, at least anxiety behind all the doors. But that would have to be risked.

When Gregor's body already projected halfway out of bed--the new method was more of a game than a struggle, he only had to keep on rocking and jerking himself along--he thought how simple everything would be if he could get some help. Two strong persons--he thought of his father and the maid--would have been completely sufficient; they would only have had to shove their arms under his arched back, in this way scoop him off the bed, bend down with their burden, and then just be careful and patient while he managed to swing himself down onto the floor, where his little legs would hopefully acquire some purpose. Well, leaving out the fact that the doors were locked, should he really call for help? In spite of all his miseries, he could not repress a smile at this thought.

He was already so far along that when he rocked more strongly he could hardly keep his balance, and very soon he would have to commit himself, because in five minutes it would be a quarter past seven--when the doorbell rang. "It's someone from the firm," he said to himself and almost froze, while his little legs only danced more quickly. For a moment everything remained quiet. "They're not going to answer," Gregor said to himself, captivated by some senseless hope. But then, of course, the maid went to the door as usual with her firm stride and opened up. Gregor only had to hear the visitor's first word of greeting to know who it was--the office manager himself. Why was only Gregor condemned to work for a firm where at the slightest omission they immediately suspected the worst? Were all employees louts without exception, wasn't there a single loyal, dedicated worker among them who, when he had not fully utilized a few hours of the morning for the firm, was driven half-mad by pangs of conscience and was actually unable to get out of bed? Really, wouldn't it have been enough to send one of the apprentices to find out--if this prying were absolutely necessary--did the manager himself have to come, and did the whole innocent family have to be shown in this way that the investigation of this suspicious affair could be entrusted only to the intellect of the manager? And more as a result of the excitement produced in Gregor by these thoughts than as a result of any real decision, he swung himself out of bed with all his might. There was a loud thump, but it was not a real crash. The fall was broken a little by the carpet, and Gregor's back was more elastic than he had thought, which explained the not very noticeable muffled sound. Only he had not held his head carefully enough and hit it; he turned it and rubbed it on the carpet in anger and pain.
"""
}
